# Generated by Django 5.0.1 on 2024-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chat_query_reply_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(null=True)),
                ('file_identifier', models.TextField(null=True)),
                ('_type', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('logs', models.TextField(null=True)),
                ('reason', models.TextField(null=True)),
            ],
        ),
    ]
