# Generated by Django 5.0.1 on 2024-01-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.AddField(
            model_name='source',
            name='search_target',
            field=models.CharField(default='SystemDB', max_length=20),
        ),
    ]
