# Generated by Django 5.0.1 on 2024-02-02 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userdocuments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('LLM_ACTION', 'LLM_ACTION'), ('ARGUMENT_FROM_OPINION', 'ARGUMENT_FROM_OPINION'), ('BRIEF', 'BRIEF')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='value',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='SelectedOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_id', models.TextField()),
                ('case_name', models.TextField()),
                ('absolute_url', models.TextField()),
                ('date_filed', models.TextField()),
                ('status', models.TextField()),
                ('citations', models.TextField()),
                ('summary', models.TextField()),
                ('generated_argument', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('court_name', models.TextField()),
                ('court_term', models.TextField()),
                ('petitioner_name', models.TextField()),
                ('respondent_name', models.TextField()),
                ('title_of_brief', models.TextField()),
                ('submitting_entity', models.TextField()),
                ('attorneys', models.TextField()),
                ('questions_presented', models.TextField()),
                ('table_of_authorities', models.TextField()),
                ('statement_of_case', models.TextField()),
                ('summary_of_arguments', models.TextField()),
                ('conclusion', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BriefArguments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('user_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='bot.userbrief')),
            ],
        ),
    ]
