# Generated by Django 5.0.1 on 2024-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_reply_options_remove_reply_reply_reply_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrief',
            name='attorneys',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='court_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='court_term',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='petitioner_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='questions_presented',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='respondent_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='submitting_entity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='table_of_authorities',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='title_of_brief',
            field=models.TextField(null=True),
        ),
    ]
