# Generated by Django 5.0.1 on 2024-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_userbrief_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrief',
            name='questions_presented',
            field=models.JSONField(null=True),
        ),
    ]
