# Generated by Django 5.0.1 on 2024-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_userbrief_questions_presented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefarguments',
            name='description',
            field=models.JSONField(null=True),
        ),
    ]
