# Generated by Django 5.0.1 on 2024-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_userbrief_statement_of_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrief',
            name='summary_of_arguments',
            field=models.JSONField(null=True),
        ),
    ]
