# Generated by Django 5.0.1 on 2024-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_userbrief_summary_of_arguments'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True )),
            ],
        ),
    ]
