# Generated by Django 5.0.1 on 2024-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedopinion',
            name='docket_reference',
            field=models.TextField(null=True),
        ),
    ]
