# Generated by Django 5.0.1 on 2024-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_selectedopinion_docket_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedopinion',
            name='court_name',
            field=models.TextField(null=True),
        ),
    ]
