# Generated by Django 5.0.1 on 2024-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_selectedopinion_court_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('CourtBrief', 'CourtBrief'), ('UserResearch', 'UserResearch')], default='CourtBrief', max_length=50),
        ),
    ]
