# Generated by Django 5.0.1 on 2024-04-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_chat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('usage_cost_in_cents', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='bot.reply')),
            ],
        ),
    ]
